[[Sites]]
Name = "ZDF"
URL = "https://www.zdf.de/spielfilm-highlights-104"
Title = "ZDF Spielfilm-Highlights"
SiteDescription = "Internationale Filme mit spannenden und emotionalen Geschichten. Ob Krimi, Drama, Komödie, Lovestory oder Thriller, für jeden Geschmack wird etwas geboten."
ItemStart = "teaser-tile"
ItemEnd = "</a></div>"
LinkStart = "href=\""
LinkEnd = "\""
TitleStart = "<h3 class=\"f1jvuh3p t1mx31h9\">"
TitleEnd = "</h3>"
DescriptionStart = ""
DescriptionEnd = ""
