[[Sites]]
Name = "ZDF"
URL = "https://www.zdf.de/filme/spielfilm-highlights"
Title = "ZDF Spielfilm-Highlights"
SiteDescription = "Internationale Filme mit spannenden und emotionalen Geschichten. Ob Krimi, Drama, Komödie, Lovestory oder Thriller, für jeden Geschmack wird etwas geboten."
ItemStart = "data-sizes=\"auto\" alt="
ItemEnd = "class=\"teaser-title-link m-clickarea-action js-track-click\""
LinkStart = "<a href=\""
LinkEnd = "\""
TitleStart = "title=\""
TitleEnd = "\""
DescriptionStart = "\""
DescriptionEnd = "\">"
